name: 'Hello World Docker Action'
description: 'Hello.'
inputs:
  who-to-greet:
    description: 'Greetings'
    required: true
    default: 'world'
outputs:
  time:
    description: 'time'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
